platform: linux
image_resource:
  type: registry-image
  source:
    repository: docker
inputs:
  - name: ips-ui-git
  - name: ips-repo
run:
  path: ips-repo/tasks/build_image_ui/task.sh
params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_ROLE_ARN:
  ECR_REPO: